apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: api-secrets-tim  # exemple : <NOM> = tim
  namespace: exercices
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: gcp-secret-store-tim
    kind: SecretStore
  target:
    name: api-secrets-tim
    creationPolicy: Owner
  data:
    # Sync DB password from GCP Secret Manager
    - secretKey: DB_PASSWORD
      remoteRef:
        key: training-db-password
    # Sync API key from GCP Secret Manager
    - secretKey: API_KEY
      remoteRef:
        key: training-api-key
