apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gcp-secret-store-tim  # exemple : <NOM> = tim
  namespace: exercices
spec:
  provider:
    gcpsm:
      projectID: "cloud-447406"
      auth:
        workloadIdentity:
          clusterLocation: "europe-west9-b"
          clusterName: "training-cluster"
          serviceAccountRef:
            name: "training-apps"
