apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secret-store
  namespace: exercices
spec:
  provider:
    gcpsm:
      projectID: "cloud-447406"
      auth:
        workloadIdentity:
          clusterLocation: "europe-west9"
          clusterName: "training-cluster"
          serviceAccountRef:
            name: "eso-service-account"
