apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: exercices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: europe-west9-docker.pkg.dev/cloud-447406/training/api:v1
          ports:
            - containerPort: 8080
          env:
            - name: ENVIRONMENT
              value: "training"
            - name: DB_HOST
              value: "postgres.exercices.svc.cluster.local"
          # Inject all keys from the Secret as environment variables
          envFrom:
            - secretRef:
                name: db-credentials
