apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-<NOM>  # Remplacez <NOM> par votre prenom
  namespace: exercices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-<NOM>
  template:
    metadata:
      labels:
        app: api-<NOM>
    spec:
      containers:
        - name: api
          image: europe-west9-docker.pkg.dev/cloud-447406/training/api:v1
          ports:
            - containerPort: 8080
          env:
            - name: ENVIRONMENT
              value: training
            # TODO: add DATABASE_URL environment variable
            # Format: postgres://admin:training-password@postgres-<NOM>.exercices.svc.cluster.local:5432/training?sslmode=disable
