apiVersion: v1
kind: Service
metadata:
  name: postgres-<NOM>  # Remplacez <NOM> par votre prenom
  namespace: exercices
spec:
  # TODO: make this a headless service (set clusterIP to None)
  selector:
    app: postgres-<NOM>
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
