apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-<NOM>  # Remplacez <NOM> par votre prenom
  namespace: exercices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-<NOM>
  template:
    metadata:
      labels:
        app: api-<NOM>
    spec:
      containers:
        - name: api
          image: europe-west9-docker.pkg.dev/cloud-447406/training/api:v1
          ports:
            - containerPort: 8080
          env:
            - name: ENVIRONMENT
              value: "training"
          # The K8s Secret "api-secrets-<NOM>" is auto-created by the ExternalSecret
          envFrom:
            - secretRef:
                name: api-secrets-<NOM>
