apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: api-secrets-<NOM>  # Remplacez <NOM> par votre prenom
  namespace: exercices
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: gcp-secret-store-<NOM>
    kind: SecretStore
  # TODO: define the target K8s Secret name
  # target:
  #   name: api-secrets-<NOM>
  #   creationPolicy: Owner
  # TODO: add data entries to sync from GCP Secret Manager
  # data:
  #   - secretKey: <K8S_SECRET_KEY>
  #     remoteRef:
  #       key: <GCP_SECRET_NAME>
