apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secret-store
  namespace: exercices
spec:
  # TODO: configure the provider
  # provider:
  #   gcpsm:
  #     projectID: "<PROJECT_ID>"
  #     auth:
  #       workloadIdentity:
  #         clusterLocation: "<REGION>"
  #         clusterName: "<CLUSTER_NAME>"
  #         serviceAccountRef:
  #           name: "<K8S_SERVICE_ACCOUNT>"
