apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gcp-secret-store-<NOM>  # Remplacez <NOM> par votre prenom
  namespace: exercices
spec:
  # TODO: configure the provider
  # provider:
  #   gcpsm:
  #     projectID: "cloud-447406"
  #     auth:
  #       workloadIdentity:
  #         clusterLocation: "europe-west9-b"
  #         clusterName: "training-cluster"
  #         serviceAccountRef:
  #           name: "training-apps"   # SA pre-cree, deja lie a GCP par Workload Identity
